sudo: required
language: java

jdk:
  - oraclejdk8

services:
  - docker

before_script:
  - echo "User"
  - echo $DOCKER_USERNAME
  - echo DOCKER_USERNAME
  - echo "Pass"
  - echo $DOCKER_PASSWORD
  - echo DOCKER_PASSWORD

script:
  - ./docker/dockerize.sh

after_success:
  - docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
  - docker push thevite/vite_server
