sudo: required
language: java

jdk:
  - oraclejdk8

services:
  - docker

script:
  - ./docker/dockerize.sh

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push thevite/vite_server
