sudo: required
language: java

jdk:
  - oraclejdk8

services:
  - docker

script:
  - ./docker/dockerize.sh

after_success:
  - docker images
  - docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
  - docker push vite-server
